name: generate breakout svg

on:
  schedule:
    - cron: "0 11 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-svg:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: generate SVG
        uses: cyprieng/github-breakout@v1
        with:
          github_username: ${{ github.repository_owner }}
          github_token: ${{ secrets.USER_TOKEN }}

      - name: Move generated SVGs to temp
        run: |
          mkdir -p /tmp/breakout-images
          mv output/light.svg /tmp/breakout-images/breakout-light.svg
          mv output/dark.svg /tmp/breakout-images/breakout-dark.svg

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and force-push SVGs to target branch
        run: |
          mv /tmp/breakout-images/* assets/img/
          git add assets/img/breakout-dark.svg
          git add assets/img/breakout-light.svg
          git commit -m "Update GitHub breakout SVGs" || echo "No changes to commit"
          git pull --rebase origin main
          git push
