name: Update stats

on:
  schedule:
    - cron: "0 11 * * *" # every 24 hours
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      message:
        type: string
        required: false
        description: "Hi!"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate README.md
        uses: gill876/profile-readme-stats@master
        with:
          token: ${{ secrets.USER_TOKEN }}
      - name: Generate README.ja.md
        uses: gill876/profile-readme-stats@master
        with:
          token: ${{ secrets.USER_TOKEN }}
          template: ./TEMPLATE.ja.md
          readme: ./README.ja.md
      - name: Update README.md
        shell: bash
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
            git config user.name 'gill876'
            git config user.email 'coolgill12@gmail.com'
            git add *.md
            git commit -m "Update README.md"
            git push
          fi
